name: Devops class

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Step to install specific python version
        uses: actions/setup-python@v3
        with:
          python-version: 3.13

      - name: Listing the files w/ an example
        run: |
          echo $SHELL
          ls -a

      - name: Dependancies installation
        run: |
          pip install -r requirements.txt
          python -m pip install flake8

      - name: Lint test
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Pytest
        run: |
          python -m pytest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4

      - name: Logging into docker
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USR}}
          password: ${{secrets.DOCKER_PWD}}

      - name: Building and pushing image
        run: |
          docker build -t ${{secrets.DOCKER_USR}}/fnl:${{github.sha}} .
          docker push ${{secrets.DOCKER_USR}}/fnl:${{github.sha}}

      - name: Deploying container app
        uses: azure/webapps-deploy@v2
        with:
          app-name: "phdevopsapp"
          publish-profile: ${{secrets.AZURE_WEBAPP_PUBLISH_PROFILE}}
          images: ${{secrets.DOCKER_USR}}/fnl:${{github.sha}}
