name: Devops class

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Step to install specific python version
        uses: actions/setup-python@v3
        with:
          python-version: 3.13

      - name: Listing the files w/ an example
        run: |
          echo $SHELL
          ls -a
